### ISSUE TITLE
"Listening" or "Watching"

### ISSUE THREAD

**Issue by jacobrae** [lolamtisch/Discord-RPC-Pack#5]
Is there no way to set it to say "Listening" or "Watching" depending on the context? I've seen bots set to "listening" and "watching" before as well as "playing" like they normally are. Is this possible? I'd also like to be able to set it to not show my presence for Youtube sometimes. Can you add options to toggle either website to show or not? I think this might be helpful if you add any more websites in the future.

**Comment by lolamtisch** [comment]
There is no way to change it. Bots use presences, which are a different thing and are bot exclusive.

You can mute websites in the main extension popup. Just open youtube start a video and then click on this ring:
![image](https://user-images.githubusercontent.com/12599334/70696490-1b92e180-1cc4-11ea-83e7-32027ca16f55.png)

Just request new pages as issue and with a bit of luck someone of us adds it.
