### ISSUE TITLE
Twitch VOD support?

### ISSUE THREAD

**Issue by tryoutuser** [lolamtisch/Discord-RPC-Pack#8]
Hello, new user here.
I found this neat extension while i was looking for alternative from heavy resource hog premid.
I don't care if it can't show when i'm on subscription feed page, library page, home page, trending, etc but it works for showing off what is playing. Keep this repo up and watch the issues for further actions!

Here is my wish, can you add twitch VOD support in your RPC pack?

Just make it look like playing youtube videos. 
For live streams can be implemented later as i don't really watch the live ones frequently.

Thank you man!

**Comment by lolamtisch** [comment]
I moved it to the correct repository.

Twitch is in the finishing touches here: https://github.com/lolamtisch/Discord-RPC-Pack/tree/twitch
It should show 90% of the pages correctly. I will probably release it someday this week. If you want you could download it from the branch until then.

**Comment by lolamtisch** [comment]
Small correction:

I will probably push the update back to next week. I remembered that i wanted to add party/discord invite support to twitch.

**Comment by tryoutuser** [comment]
So when it's out all i have to do is just update RPC pack extension right?
Got it. Thanks man!

**Comment by henrik9999** [comment]
yeah or just let chrome or whatever browser you are using auto update it

**Comment by lolamtisch** [comment]
After 2 weeks trying to publish the update on the chrome store it is finally in. They are very vague what they really want to be changed.
